<a href="https://colab.research.google.com/github/sribalajimsb7/Digit-Recognizer/blob/master/modelfinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
mnist = tf.keras.datasets.mnist
(x_train,y_train), (x_test,y_test) = mnist.load_data()

In [ ]:
x_train , x_test = x_train / 255.0 , x_test / 255.0
x_train = tf.keras.utils.normalize(x_train, axis=-1)
x_test = tf.keras.utils.normalize(x_test,axis=-1)
print(y_train)

[5 0 4 ... 5 6 8]


In [ ]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28,28)))
model.add(tf.keras.layers.Dense(units=512 , activation='relu'))
model.add(tf.keras.layers.Dense(units=512 , activation='relu'))
# model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=10 , activation='softmax'))
model.compile(optimizer='adam' , loss =tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['sparse_categorical_accuracy'])

In [ ]:
mc = tf.keras.callbacks.ModelCheckpoint('model_digits{epoch:d}.h5', 
                                     save_weights_only=False, period=10)

In [ ]:
history = model.fit(x_train,y_train,epochs=10, callbacks=[mc])

Epoch 1/10
1875/1875 [==============================] - 14s 7ms/step - loss: 1.5593 - sparse_categorical_accuracy: 0.9057
Epoch 2/10
1875/1875 [==============================] - 14s 7ms/step - loss: 1.5075 - sparse_categorical_accuracy: 0.9542
Epoch 3/10
1875/1875 [==============================] - 14s 7ms/step - loss: 1.4988 - sparse_categorical_accuracy: 0.9625
Epoch 4/10
1875/1875 [==============================] - 14s 7ms/step - loss: 1.4952 - sparse_categorical_accuracy: 0.9658
Epoch 5/10
1875/1875 [==============================] - 14s 8ms/step - loss: 1.4929 - sparse_categorical_accuracy: 0.9682
Epoch 6/10
1875/1875 [==============================] - 18s 10ms/step - loss: 1.4914 - sparse_categorical_accuracy: 0.9697
Epoch 7/10
1875/1875 [==============================] - 14s 8ms/step - loss: 1.4895 - sparse_categorical_accuracy: 0.9714
Epoch 8/10
1875/1875 [==============================] - 15s 8ms/step - loss: 1.4878 - sparse_categorical_accuracy: 0.9730
Epoch 9/10
1875/1875 [=

In [ ]:
#evaluate saved model vs original model
m_new=tf.keras.models.load_model('model_digits10.h5')
# saved model
m_new.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 1.4923 - sparse_categorical_accuracy: 0.9687


[1.4922959804534912, 0.9686999917030334]

In [ ]:
#current model
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 1.4923 - sparse_categorical_accuracy: 0.9687


[1.4922959804534912, 0.9686999917030334]

In [ ]:
y_pred = model.predict_classes(x_test)
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
y_pred[0]

7

In [ ]:
np.argmax(y_pred[0])

0

In [ ]:
np.argmax(model.predict(x_test), axis=-1)

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
# Evaluation
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
accuracy_score(y_pred,y_test)

0.9687

In [ ]:
confusion_matrix(y_pred,y_test)

array([[ 968,    0,    8,    2,    2,    1,    3,    1,    5,    4],
       [   0, 1115,    2,    0,    0,    0,    2,    2,    0,    3],
       [   0,    1,  993,    6,    0,    0,    0,    3,    2,    0],
       [   1,    5,    2,  974,    0,    5,    0,    6,    6,    4],
       [   0,    0,    1,    0,  914,    0,    1,    3,    2,    6],
       [   1,    2,    1,   20,    0,  876,   11,    0,   12,    7],
       [   4,    2,    1,    0,    7,    4,  938,    0,    0,    1],
       [   0,    1,    8,    4,    4,    0,    0,  995,    2,    4],
       [   5,    9,   16,    3,    0,    2,    3,    2,  935,    1],
       [   1,    0,    0,    1,   55,    4,    0,   16,   10,  979]])

In [ ]:
model.get_weights()

[array([[ 0.02489271,  0.06449917,  0.05173127, ..., -0.04748466,
         -0.05929786, -0.05453691],
        [ 0.0116111 , -0.0534731 ,  0.02782352, ..., -0.06581153,
          0.05960859, -0.05306035],
        [-0.03042852, -0.04016952, -0.00464817, ..., -0.03066124,
         -0.02944859,  0.0473662 ],
        ...,
        [ 0.05152121, -0.0541777 , -0.05497766, ..., -0.01150032,
         -0.05001651, -0.04703441],
        [-0.00128449,  0.03218361,  0.00528945, ..., -0.05527152,
          0.04153222,  0.00656661],
        [ 0.00474481, -0.0242262 ,  0.0004812 , ..., -0.01769368,
         -0.05133527, -0.03819447]], dtype=float32),
 array([ 0.02529967,  0.00855865,  0.03143314, -0.06215484,  0.03365522,
        -0.0142504 , -0.03404409, -0.03582941,  0.01095901, -0.05903916,
        -0.04131829, -0.04520024, -0.00286788, -0.06170639, -0.01648182,
        -0.03070845, -0.05148931, -0.03555294, -0.08448454, -0.06227366,
         0.03034926, -0.05983386, -0.07178883, -0.07111876, -0.014

In [ ]:
loss , accuracy = model.evaluate(x_test , y_test)

313/313 [==============================] - 1s 3ms/step - loss: 1.4923 - sparse_categorical_accuracy: 0.9687


In [ ]:
print(accuracy)

0.9686999917030334


In [ ]:
print(loss)

1.4922959804534912


In [ ]:
model.save('model.h5')